test: replace mojaloop connector with sdk-scheme-adapter
pm4ml/mojaloop-payment-manager-ui pull request #21
Opened 2022-04-21 19:58 UTC by kleyow

2022-05-16 08:03 UTC, mdebarros requested changes
See my questions.

2022-05-16 08:03 UTC, mdebarros commented on on-premise-deploy/testing-toolkit/environments/environment.json
> -    "toFirstName": "PayeeFirst",
So this name will fail the tests?

2022-05-16 13:20 UTC, kleyow commented on on-premise-deploy/testing-toolkit/environments/environment.json
> -    "fromFirstName": "Firstname-Test",
Correct.

2022-05-16 13:20 UTC, kleyow commented on on-premise-deploy/testing-toolkit/environments/environment.json
> -    "toFirstName": "PayeeFirst",
Correct.

2022-05-16 15:23 UTC, kleyow commented
Sam mentioned in todays meeting to just call this a breaking change and to just move forward with the fspiop standard. @mdebarros @elnyry-sam-k

2022-05-17 09:38 UTC, mdebarros commented
> Sam mentioned in todays meeting to just call this a breaking change and to just move forward with the fspiop standard. @mdebarros @elnyry-sam-k

Ok, so no changes needed except making not of the breaking change?

2022-05-17 14:08 UTC, merged